name: Build package and push to PyPi

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON: "3.12"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed so hatch-vcs can read git tags.

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up python ${{ env.PYTHON }}
        run: uv python install ${{ env.PYTHON }}

      - name: Build package
        run: uv build

      - name: Publish package
        if: github.event_name != 'workflow_dispatch'
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dist
          path: dist/
